apiVersion: v1
kind: Pod
metadata:
  name: emptydir
  labels:
    project: roboshop
    environment: dev
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80
      volumeMounts:
        - name: empty-volume
          mountPath: /var/log/nginx/
    - name: almalinux
      image: almalinux:9
      command: ["sleep","1000"]
      volumeMounts:
        - name: empty-volume
          mountPath: /mnt/nginx-logs
          readOnly: true
  volumes:
    - name: empty-volume
      emptyDir:
        sizeLimit: 500Mi 
