apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    project: roboshop
    environment: dev
    cloud: awseksctl
spec:
  containers:
    - name: nginx
      image: nginx # it will pull from docker hub
          