apiVersion: v1
kind: Pod
metadata:
  name: annotation-v1
  annotations:
    builder: "Jenkins v2.4"
    config.json: '{"rate-limiting": true, "max-connections": 100}'
spec:
  containers:
    - name: nginx
      image: nginx  