apiVersion: v1
kind: Pod
metadata:
  name: resource-v1
spec:
  containers:
    - name: nginx
      image: nginx
      resources:
        requests: # soft limit
          cpu: "250m"  #1000millicore/m =1cpu
          memory: "128Mi"
        limits: # hard limit
          cpu: "300m"
          memory: "256Mi"