apiVersion: v1
kind: Service
metadata:
  name: nodeport
  labels:
    project: roboshop
    component: nodeport
    tier: servicenp
spec:
  type: NodePort
  selector:
    project: roboshop
    component: nodeport
    tier: servicenp
  ports:
    - protocol: TCP
      port: 80  # Accessible internally via ClusterIP:80 service port
      targetPort: 80 # Port the app is listening on inside the container
      nodeport: 3008 # Accessible externally via NodeIP:3008
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-NodePort
  labels:
    project: roboshop
    component: nodeport
    tier: servicenp
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80      
