apiVersion: v1
kind: Service
metadata:
  name: pod-loadbalancer
  labels:
    project: roboshop
    component: loadbalancer
    tier: poodlb
spec:
  type: LoadBalancer
  selector:
    project: roboshop  # Route traffic to Pods with this label
    component: LoadBalancer
    tier: poodlb
  ports:
    - protocol: TCP
      port: 80  # The port clients connect to on the LoadBalancer IP
      targetPort: 80 # app listern port inside traget container
      nodePort: 30009
---
apiVersion: v1
kind: Pod
metadata:
  name: podlb
  labels:
    project: roboshop
    component: LoadBalancer
    tier: poodlb
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80  
